from django.conf import settings

NGINX_PUSH_STREAM_PUB_HOST = getattr(settings, "NGINX_PUSH_STREAM_PUB_HOST", '127.0.0.1')
NGINX_PUSH_STREAM_PUB_PORT = getattr(settings, "NGINX_PUSH_STREAM_PUB_PORT", 80)

NGINX_PUSH_STREAM_SUB_HOST = getattr(settings, "NGINX_PUSH_STREAM_SUB_HOST", '127.0.0.1')
NGINX_PUSH_STREAM_SUB_PORT = getattr(settings, "NGINX_PUSH_STREAM_SUB_PORT", 80)

NGINX_PUSH_STREAM_PROTOCOL = getattr(settings, "NGINX_PUSH_STREAM_PROTOCOL", 'http')
NGINX_PUSH_STREAM_PUB_PREFIX = getattr(settings, "NGINX_PUSH_STREAM_PUB_PREFIX", 'my-app')
