FROM python:3

ENV PYTHONUNBUFFERED 1

ENV PYTHONPATH ./test_project:.

ENV NGINX_PUSH_STREAM_PUB_HOST webserver
ENV NGINX_PUSH_STREAM_PUB_PORT 80

RUN mkdir /app

WORKDIR /app

RUN pip install uwsgi Django

COPY nginx_push_stream /app/nginx_push_stream

COPY test_project /app/test_project

RUN pip install -r /app/test_project/requirements.txt

RUN python test_project/manage.py collectstatic --noinput

ENTRYPOINT uwsgi --http 0.0.0.0:9090 --socket 0.0.0.0:8080 --static-map /static=/app/test_project/staticroot -w test_project.wsgi
